### PR TITLE
Enable extension

### PR DESCRIPTION
**Pull request by schkovich**
@igalic squashed :smile: 

refs #148 #142 #139 #76

### CODE REVIEW

**Comment by darthsteven** [comment]
This doesn't seem to address #142 fully, because extensions that don't come from pecl still don't get their config symlinked into the correct place.

**Comment by schkovich** [comment]
@darthsteven It does. The problem is specific to PECL installation. If an deb package does not symlink extension config then the bug report should be filed against the package.

**Comment by darthsteven** [comment]
Okay, fair enough.

**Comment by schkovich** [comment]
Priority whitespace problem was fixed in next stable Debian [php-defaults_47](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=783246#15) but since that change is not going to be included in the default Ubuntu repositories anytime soon I'm leaving a small [hack](https://github.com/jippi/puppet-php/pull/162/files#diff-6242cc90480db4a4659a562b4c1b692eR62) that inserts mandatory whitespace.

**Pull request merged**
