### PR TITLE
Install PHPUnit via phar just like Composer

### PR DESCRIPTION
**Pull request by westonruter**
This copies the approach used to install Composer via phar.

Will fix https://github.com/Automattic/vip-quickstart/issues/289

### CODE REVIEW

**Comment by jippi** [comment]
seems legit :+1:

**Comment by igalic** [comment]
proposal: replace exec-wget, with @maestrodev's [wget](https://github.com/maestrodev/puppet-wget).
(here, and in composer)

**Comment by jippi** [comment]
won't that make it pain in the ass for people to install dependencies ?

**Comment by joshbetz** [comment]
An external dependency to make wget easier seems like overkill. @jippi is there anything else that needs to happen before this is merged?

**Comment by jippi** [comment]
Other than the ensure should be absent = delete the file again I think its good

**Comment by westonruter** [comment]
I confess I am not a *puppet master*. Where would "absent = delete" go?

**Comment by jippi** [comment]
``ensure = absent`` should be in the primary manifest, and just delete the composer file :)

**Comment by westonruter** [comment]
Like b6e83bd?

**Comment by joshbetz** [comment]
Probably something like:

```
if ( 'absent' == $ensure ) {
  file { $destination:
    path     => $destination,
    ensure => absent
  }
} else {
  // Install phpunit
}
```

**Comment by westonruter** [comment]
@joshbetz I'm out of my depth here. I'll leave it with you.

**Comment by joshbetz** [comment]
Thanks @westonruter. It looks like https://github.com/schkovich/puppet-php/commit/ea1ead55f02c927437abc7b8f4c84708866a7261 breaks Quickstart too so hopefully we can get that reverted. Otherwise I'll look into a workaround.

**Comment by igalic** [comment]
i believe this is now covered by #128

**Comment by igalic** [comment]
i believe this is now covered by #128
thank you @joshbetz and @westonruter!

**Pull request closed without merging**
