### PR TITLE
Exensions Installed Using Pecl Provider are not Enabled

### PR DESCRIPTION
**Pull request by schkovich**
A proposal on how to tackle the problem in a bit more generic way. It's mixture of @jippi's [idea](https://github.com/jippi/puppet-php/pull/74#issuecomment-44627539) given in issue #74 thread, @igalic's solution given in #116 and a workaround the hiera and php5(dis)enable incomparability problem described in [bug #783246](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=783246).

Related: #142 #139 #102 #76 #74

### CODE REVIEW

**Comment by jippi** [comment]
looks legit to me :)

**Comment by schkovich** [comment]
Well, it does look legit. :) However, it would be good to define a type that will encapsulate command creation/execution logic depending on PHP version. It will be nice to create unit tests as well. Finally there are twenty commits referencing each step I made. None of those commits have a place in upstream/master. Except the last one of course. :)

**Comment by jippi** [comment]
What do you think @igalic ?

**Comment by igalic** [comment]
needs [squash](http://www.git-scm.com/book/en/Git-Tools-Rewriting-History#Squashing-Commits)

**Comment by schkovich** [comment]
@igalic I am not happy with _disenable_ either. I would gladly change if you can come with one.

Aside from documentation I would add tests as well.

Absolutely, squash is mandatory. I did not intend to create pull request but provide a example to discuss.

**Comment by igalic** [comment]
@schkovich perhaps i should also have mentioned that other than the criticism, i'm actually quite happy with the way this is taking.

**Comment by schkovich** [comment]
squashed version of this change in #162 

@igalic I did not get a better name. :( I added doc blocks and assert_private.

**Pull request closed without merging**
