### PR TITLE
Install PHPUnit via Phar

### PR DESCRIPTION
**Pull request by joshbetz**
See #124

### CODE REVIEW

**Comment by igalic** [comment]
@joshbetz i still think that @maestrodev's [wget](https://github.com/maestrodev/puppet-wget) is a *good* thing to have, because unllike your exec, their exec actuall handles all edge-cases.

to quote [Green's 10th Rule of Programming](http://www.c2.com/cgi/wiki?GreenspunsTenthRuleOfProgramming)
> Any sufficiently complicated C or Fortran program contains an ad-hoc, informally-specified, bug-ridden, slow implementation of half of CommonLisp.

;)

in puppet we have modules, and using them is as simple as adding a line into a file, so i think we should.

***

that said, we can leave it for another time, with a specific pr covering the conversion.

**Comment by jippi** [comment]
:+1:

**Comment by igalic** [comment]
we should also make a mental now to extract the `mode`

**Comment by igalic** [comment]
thank you @joshbetz

**Comment by jippi** [comment]
:clap:

**Pull request merged**
