### PR TITLE
Ensure greater consistency between php extensions

### PR DESCRIPTION
**Pull request by Vincent--**
- Use php::params::config_root_ini for ini files path :
    * imap
    * ldap
    * memcache
    * memcached
- Add default settings for all extension
- Remove unnecessary settings and comments

### CODE REVIEW

**Comment by igalic** [comment]
this is legit, but should be done differently imo ~_~
we shouldn't be having a params class for each php extension to begin with.

i'll merge this for now, thank you very much @Vincent-- !

**Comment by Vincent--** [comment]
I totally agree with you, Igor ;-)
Happy to help when you'll have chosen the correct implementation for doing that :-)

**Comment by Vincent--** [comment]
What about https://github.com/ripienaar/puppet-module-data/ ?

**Comment by igalic** [comment]
@Vincent-- i don't really think that'll be necessary…

**Comment by schkovich** [comment]
@igalic however since in early January @ripienaar maintainer of the project @Vincent-- suggested announced : 

> There is now native support for this feature in Puppet 4 and this repo is now officially deprecated and moving to unmaintained.

once we officially declare Puppet 4 support (unofficially I am using my fork on v 4.* for a few months though not yet in production)  implementing _module data_ pattern might bring improvements. :smile:

**Comment by jippi** [comment]
I really don't spend much time maintaining this any more - if any of you guys want commit-bit to the repo, let me know and id happily give it :)

**Comment by schkovich** [comment]
Could we do better than [Mayflower](https://github.com/mayflower/puppet-php)? 

Mayflower module diverted far away. They have wider support across OS-es, they simplified API and put hiera usage forward. However, I am not sure if they made right design decisions.

Usage of the module is dramatically down since the last release was almost two years ago. 

What do you think @igalic?

**Comment by jippi** [comment]
@schkovich just a heads up that I'm personally only using my module with `hiera` - its just poorly documented atm :)

**Comment by schkovich** [comment]
im using it with hiera as well. :smile: 

yes, this module is still placed well and used widely. we need to reach decision quickly otherwise the module might sink into oblivion since it is not maintained and there are no new releases.

**Comment by schkovich** [comment]
@jippi, @igalic I am willing to dedicate more time to maintaining the module. Could we discuss how shall we proceed and what will be my responsibilites?

**Comment by jippi** [comment]
@schkovich sure thing! do you hang out in hangops slack?

**Comment by schkovich** [comment]
nope. i guess that that i would need invitation to join hangops slack @jippi. :smile:

**Comment by jippi** [comment]
@schkovich here you go ! https://signup.hangops.com/ :)

**Pull request merged**
