### PR TITLE
Mange PHP-FPM configuration once the package is installed

### PR DESCRIPTION
**Pull request by schkovich**
==> default: Error: /Stage[main]/Php::Fpm/File[/etc/php5/fpm/php-fpm.conf]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory - /etc/php5/fpm/php-fpm.conf20150216-9250-13qqa16.lock at 99:/home/vagrant/opt/puppet/modules/php/manifests/fpm.pp

Catalog run will fail case the PHP-FPM package is manged before the package itself is installed. I just added require parameter to file definition.

P. S. Don't get confused over branch name. I was on some xdebug issue and I named the branch on auto-pilot. ;)

### CODE REVIEW

**Comment by igalic** [comment]
@schkovich this looks simple enough, once it's figured out ;) so could you please squash it down to one commit please?

**Comment by jippi** [comment]
:+1:

**Comment by schkovich** [comment]
New pull request created instead having a single commit. Refs #130

**Comment by igalic** [comment]
okay!

**Pull request closed without merging**
