### PR TITLE
Fixes issue #102 by replacing hard coded value with fact

### PR DESCRIPTION
**Pull request by it-ony**
Hi, 

I created a custom fact, to read out the php extension version. I reference the version in the xdebug parameters module.

Cheers,
Tony

### CODE REVIEW

**Comment by danygielow** [comment]
+1
I would really like to see this merged.

**Comment by igalic** [comment]
two comments from my side:

i'd like to reduce the number of useless pipes in that `Facter::Util::Resolution.exec` call by simply using `php -i | awk '/PHP Extension =/{print $4}'`

i'd also like to see those four commits [squashed down](http://www.git-scm.com/book/en/Git-Tools-Rewriting-History#Squashing-Commits) to one.

if @it-ony isn't up for that (anymore), do you wanna take over @danygielow?

**Comment by jippi** [comment]
Also there should be a default value else you get weird results on first run when php is not installed and thus can't be exported as a fact

**Comment by igalic** [comment]
fixed by #123. thanks @danygielow and @it-ony!

**Pull request closed without merging**
